check in docker too

diff --git a/check-dns-bits b/check-dns-bits
--- a/check-dns-bits
+++ b/check-dns-bits
@@ -7,23 +7,31 @@ main() {
 
   cat /etc/resolv.conf
   echo "----"
-  cat /etc/network/interfaces
-  echo "----"
-  git config --list
-  echo "----"
+  #cat /etc/network/interfaces
+  #echo "----"
 
   for try in 0 1 2 3; do
     for nameserver in 8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1 169.254.169.254; do
       for h in github.com s3-us-west-1.amazonaws.com; do
+
         echo "---> $(date -u): try ${try} ${h} via ${nameserver}:"
         if ! dig +short "@${nameserver}" "${h}"; then
           echo "    x Failed to lookup ${h} via ${nameserver}"
           failures=$((failures + 1))
         fi
+        echo
+
         if ! dig -6 +short "@${nameserver}" "${h}"; then
           echo "    x Failed to lookup ${h} via ${nameserver}"
           failures=$((failures + 1))
         fi
+        echo
+
+        if ! docker run -ti tutum/dnsutils dig +short "@${nameserver}" "${h}"; then
+          echo "    x Failed to lookup ${h} via @${nameserver} (docker)"
+          failures=$((failures + 1))
+        fi
+        echo
       done
     done
   done
@@ -34,9 +42,10 @@ main() {
   fi
 
   echo "===> Much Success"
-  exit 0
+  #exit 0
 }
 
 while true; do
     main "${@}"
+    echo "finished loop =========================================="
 done
